# Dependencies
markdown:         kramdown
highlighter:      rouge

title:            i.Gorschal
tagline:          "i.Gorschal Personal Page"
description:      "Developer resources: #Python, #Golang, #Dev, #Ops, and #DevOps tutorials, video, github projects, news, and more!"
url:              https://neegor.github.io/blog.gorschal.github.io
baseurl:          "/blog.gorschal.github.io"
root:             /

author:
  name:           "Igor Gorschal"
  email:          "gorschal@gmail.com"
  github:         neegor
  twitter:        gorschal

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
