# Dependencies
markdown:         kramdown
highlighter:      rouge

title:            i.Gorschal
tagline:          "i.Gorschal Personal Blog"
url:              https://blog.gorschal.com
baseurl:          "/"
root:             /

author:
  name:           "Igor Gorschal"
  email:          "gorschal@gmail.com"
  github:         neegor
  twitter:        gorschal

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
