# Dependencies
markdown:         kramdown
highlighter:      rouge

title:            i.Gorschal
tagline:          "i.Gorschal Personal Blog"
url:              https://neegor.github.io/blog.gorschal.github.io
baseurl:          "/blog.gorschal.github.io"
root:             /

author:
  name:           "Igor Gorschal"
  email:          "gorschal@gmail.com"
  github:         neegor
  twitter:        gorschal

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
