# Dependencies
markdown:         kramdown
highlighter:      rouge

title:            Gorschal Blog
tagline:          Gorschal Personal Blog
url:              https://blog.gorschal.com
baseurl:          /
root:             /

author:
  name:           Igor Gorschal
  email:          gorschal@gmail.com
  github:         neegor

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate